services:
  - name: users-admin-backend
    type: web
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: supersecret
      - key: DB_HOST
        value: dpg-d62u657pm1nc738hpehg-a
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: users_xdp3_user
      - key: DB_PASSWORD
        value: MgOpXs5ZwCnAeeU1qtYlIS9JCg4sQ5aA
      - key: DB_NAME
        value: users_xdp3
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: DEMO_EMAIL
        sync: false
      - key: DEMO_PASSWORD
        sync: false

  - name: users-admin-frontend
    type: web
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://authorization-app-j376.onrender.com
